In [1]:
!pip install pandas numpy seaborn

In [2]:
!which python

/c/Users/thoma/AppData/Local/Programs/Python/Python38-32/python


In [3]:
import numpy as np

In [4]:
l = [i for i in range(10)]

In [5]:
ar = np.array(l)

In [6]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
ar.min()

0

In [8]:
ar.max()

9

In [9]:
ar.mean()

4.5

In [11]:
ar.std()

2.8722813232690143

In [12]:
ar.dtype

dtype('int32')

In [13]:
m = np.array([[1,2], [3,4]]); m

array([[1, 2],
       [3, 4]])

In [14]:
m[0][1]

2

In [15]:
m.shape

(2, 2)

In [27]:
m2 = np.array([1,2,3,4,5], ndmin = 2); m2

array([[1, 2, 3, 4, 5]])

In [28]:
m2.reshape(5,1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [30]:
b = np.linspace(0, 2, 4); b

array([0.        , 0.66666667, 1.33333333, 2.        ])

In [31]:
b**2

array([0.        , 0.44444444, 1.77777778, 4.        ])

In [33]:
c = np.arange(24).reshape(2,3,4); c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [35]:
ar = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]); ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [83]:
ar[1:3,0:2] # lignes 2,3 colonnes 1,2

array([[4, 5],
       [7, 8]])

In [87]:
ar[1,:]

array([4, 5, 6])

In [91]:
ar[:,-1]

array([3, 6, 9])