# Numpy exercices pratiques
Ce notebook à pour objectif de vous faire pratiquer numpy dans toute sa généralité. 
Vous avez donc une liste de questions à faire ! Il ne faut pas hésiter à faire des recherches sur google ainsi que voir la [documentation officielle](https://docs.scipy.org/doc/numpy-1.13.0/reference/). 

#### Q1 : Importer le package numpy 

In [1]:
import numpy as np

#### Q2 : Afficher la version de numpy et la configuration 

In [2]:
np.version.version

'1.19.2'

#### Q3 : Créer un vecteur nul de taille 10

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Q4 : Créer un vecteur null de taille 10 et affecter la valeur 1 à la 4ème place (index 4) du vecteur

In [7]:
V = np.zeros(10); V[4] = 1; V

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### Q5 : Créer un vecteur Z de 40 valeurs allant de 10 à 50 

In [9]:
Z = np.linspace(10, 50, 40) ; Z

array([10.        , 11.02564103, 12.05128205, 13.07692308, 14.1025641 ,
       15.12820513, 16.15384615, 17.17948718, 18.20512821, 19.23076923,
       20.25641026, 21.28205128, 22.30769231, 23.33333333, 24.35897436,
       25.38461538, 26.41025641, 27.43589744, 28.46153846, 29.48717949,
       30.51282051, 31.53846154, 32.56410256, 33.58974359, 34.61538462,
       35.64102564, 36.66666667, 37.69230769, 38.71794872, 39.74358974,
       40.76923077, 41.79487179, 42.82051282, 43.84615385, 44.87179487,
       45.8974359 , 46.92307692, 47.94871795, 48.97435897, 50.        ])

#### Q6 : Inverser Z (le premier élément devient donc le dernier)

In [10]:
Z[::-1]

array([50.        , 48.97435897, 47.94871795, 46.92307692, 45.8974359 ,
       44.87179487, 43.84615385, 42.82051282, 41.79487179, 40.76923077,
       39.74358974, 38.71794872, 37.69230769, 36.66666667, 35.64102564,
       34.61538462, 33.58974359, 32.56410256, 31.53846154, 30.51282051,
       29.48717949, 28.46153846, 27.43589744, 26.41025641, 25.38461538,
       24.35897436, 23.33333333, 22.30769231, 21.28205128, 20.25641026,
       19.23076923, 18.20512821, 17.17948718, 16.15384615, 15.12820513,
       14.1025641 , 13.07692308, 12.05128205, 11.02564103, 10.        ])

#### Q7 : Créer une matrice 3x3 avec des valeurs comprise entre 0 et 8 

In [11]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Q8 : Créer une matrice identié 3x3 

In [12]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Q9 : Créer une matrice 3x3x3 avec des valeurs random 

TypeError: 'module' object is not callable

#### Q10 : Créer une matrice 10x10 avec des valeurs random et afficher le minimum et maximum de cette matrice

#### Q11 : Créer une matrice 5x5 avec les valeurs 1,2,3,4 en dessous de la diagonale 

#### Q12 : Créer une liste random de taille 5 et donner la somme de ses éléments  

#### Q13 : Créer une liste random de taille 5 et donner la moyenne de ses éléments

#### Q14 : En utilisant une fonction, donner la taille de la liste suivante :
```python 
l = [x for x in range(11)]
```

#### Q15 : Créer un tableau de taille 10 avec des valeurs comprises entre 0 et 1 EXCLUS 

#### Q16 : Soit deux tableau A et B de dimension 1 et de taille 5, créer A et B et afficher True si A et B sont égaux False sinon

#### Q17 : Convertir un tableau de float32 de dimension 1 et de taille 10 en un tableau de meme taille et dimension mais de type int32

#### Q18 : Normaliser une matrice random 5x5 
La normalisation d'un nombre X consiste à lui retirer sa moyenne et a diviser le tout par son écart type 

#### Q19 : Créer une matrice random `M` 2x2 et donner sa transposer 
L'opération de transposition dans une matrice consiste à échanger les lignes et le colonnes. 

#### Q20 : Écrire un petit script qui remplace un élément au hasard dans une matrice de dimension NxN

#### Q21 : Considérons une matrice de dimension (5,5,3), écrire un script qui multiplie cette matrice par une matrice de dimension (5,5)